version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - sam build --use-container
      - . ./assume-role.sh ${PIPELINE_EXECUTION_ROLE} package
      - sam deploy --stack-name ${COMPONENT_STACK_NAME}
                    --capabilities CAPABILITY_IAM
                    --region ${REGION}
                    --s3-bucket ${INFRASTRUCTURE_BUCKET_NAME}
                    --no-fail-on-empty-changeset
                    --role-arn ${CLOUDFORMATION_EXECUTION_ROLE}
